#ifndef ERRORS_H
# define ERRORS_H

#define CHAR_IS_NOT_ALLOWED_ERROR 1
#define BEFORE_OPERATION_EXPECTED_ERROR 2
#define AFTER_OPERAND_EXPECTED_ERROR 3
#define NO_ALL_BRACKETS_CLOSED_ERROR 4
#define OPENING_BRACKET_NOT_MET_ERROR 5
#define BEFORE_POINT_EXPECTED_DIGIT_ERROR 6
#define AFTER_POINT_EXPECTED_DIGIT_ERROR 7
#define AFTER_OPERATION_EXPECTED_OPERAND_ERROR 8
#define BRACKETS_IS_EMPTY_ERROR 9
#define POINT_IS_EXCESS_ERROR 10
#define ZERO_DIVISION_ERROR 11
#define POWER_ERROR 12
#define EMPTY_STRING_ERROR 13
#define VAR_NOT_DEFINED_ERROR 14
#define LEFT_PART_NOT_MET_ERROR 20
#define COMMAND_NOT_EXIST_ERROR 21
#define AFTER_COMM_NOT_EXPECTED_CHARS_ERROR 22
#define FILE_NOT_FOUND_ERROR 23
#define MUST_BE_NO_CHARS_BETWEEN_ERROR 24
#define FILE_NAME_NOT_MET_ERROR 25
#define FILE_IS_RUNNING_ERROR 26
#define EXIT_NUMBER 30

void print_error(Pair );

#endif // ERRORS_H